In [1]:
import pprint
import os
import sys
from params import get_cfg
from rnn_base import RNN
from ops import Operations
from session import run_session, restore_selection_matrixes
from data_gen import samples_generator, split_train_test
import tensorflow as tf

#get the global configuration
cfg = get_cfg() 
#instantiate containter with the operations avail for the selection
ops = Operations(cfg)
#reset graph so that tf dont complain about not found vars
tf.reset_default_graph()
#generate data 
x,y = samples_generator(cfg['train_fn'], (cfg['num_samples'], cfg['num_features']) , cfg['samples_value_rng'], cfg['seed'])
x_train, x_test, y_train, y_test = split_train_test (x, y , cfg['test_ratio'])
# instanitae the model graph
model = RNN(cfg, ops)
#restore with given path
path = './summaries/np_add-5ops/test1/model/'
_softmaxes_train, _softmax_train, _softmaxes_test, _softmax_test = restore_selection_matrixes(model, cfg, x_train, x_test, y_train, y_test, path)


timestep 0
timestep 1
timestep 2
timestep 3
timestep 4
timestep 0
timestep 1
timestep 2
timestep 3
timestep 4
[<tf.Variable 'W:0' shape=(53, 50) dtype=float64_ref>, <tf.Variable 'b:0' shape=(50,) dtype=float64_ref>, <tf.Variable 'W2:0' shape=(50, 3) dtype=float64_ref>, <tf.Variable 'b2:0' shape=(3,) dtype=float64_ref>]
norming the grads
grads are
[<tf.Tensor 'clip_by_global_norm/clip_by_global_norm/_0:0' shape=(53, 50) dtype=float64>, <tf.Tensor 'clip_by_global_norm/clip_by_global_norm/_1:0' shape=(50,) dtype=float64>, <tf.Tensor 'clip_by_global_norm/clip_by_global_norm/_2:0' shape=(50, 3) dtype=float64>, <tf.Tensor 'clip_by_global_norm/clip_by_global_norm/_3:0' shape=(3,) dtype=float64>]
num batches train: 10
num batches test: 4
INFO:tensorflow:Restoring parameters from ./summaries/np_add-5ops/test1/model/-1950


In [2]:
for softmaxe in _softmaxes_train:
    print("#####################################################################")
    print(softmaxe)

#####################################################################
[[  9.46292729e-01   2.57388580e-09   5.37072682e-02]
 [  9.99999994e-01   5.58441017e-09   3.83575439e-11]
 [  9.99980117e-01   1.20379108e-10   1.98829003e-05]
 [  9.99999988e-01   1.19878569e-08   6.46678556e-12]
 [  9.99999992e-01   5.31371984e-09   2.55593127e-09]
 [  1.00000000e+00   1.70420123e-10   1.07598480e-13]
 [  9.99997578e-01   1.59953930e-09   2.42021902e-06]
 [  9.99912867e-01   4.57195979e-10   8.71323905e-05]
 [  9.99999999e-01   6.45290394e-10   8.84849510e-12]
 [  9.99999997e-01   2.73443139e-09   2.02717245e-12]
 [  9.99784236e-01   1.62788867e-09   2.15762632e-04]
 [  9.76050554e-01   3.98754240e-09   2.39494425e-02]
 [  9.99915009e-01   2.02376748e-09   8.49893146e-05]
 [  9.99999998e-01   1.90892846e-09   5.25174727e-12]
 [  1.00000000e+00   1.43035043e-10   4.04568060e-13]
 [  9.99769677e-01   2.23027377e-09   2.30320912e-04]
 [  9.22476642e-01   9.37045996e-10   7.75233573e-02]
 [  9.999999

In [3]:
for softma in _softmaxes_test:
    print("#####################################################################")
    print(softma)

#####################################################################
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]


In [ ]:
_softmax_train.shape

In [ ]:
W2.shape

In [ ]:
W.shape

In [ ]:
init_state.shape

In [ ]:
b.shape

In [ ]:
b2.shape