In [16]:
import pprint
import os
import sys
from params import get_cfg
from rnn_base import RNN
from ops import Operations
from session import run_session, restore_selection_matrixes
from data_gen import samples_generator, split_train_test
import tensorflow as tf
import pickle

path = '/home/user/neural_program_synthesis/models/summaries/RNN/np_mult-5ops/200_state_size-1500_num_samples-100_batch_size-0.005_learning_rate-1000.0_grad_norm-3_num_features-True_norm/'
#get the global configuration
cfg_path = path+'cfg.p'
cfg = pickle.load(open(cfg_path, 'rb'))
#instantiate containter with the operations avail for the selection
ops = Operations(cfg)
#reset graph so that tf dont complain about not found vars
tf.reset_default_graph()
#generate data 
x,y = samples_generator(cfg['train_fn'], (cfg['num_samples'], cfg['num_features']) , cfg['samples_value_rng'], cfg['seed'])
x_train, x_test, y_train, y_test = split_train_test (x, y , cfg['test_ratio'])
# instanitae the model graph
model = RNN(cfg, ops)
#restore with given path
model_path = path+'/model'
_softmaxes_train, _softmax_train, _softmaxes_test, _softmax_test = restore_selection_matrixes(model, cfg, x_train, x_test, y_train, y_test, model_path)


timestep 0
timestep 1
timestep 2
timestep 3
timestep 4
timestep 0
timestep 1
timestep 2
timestep 3
timestep 4
[<tf.Variable 'W:0' shape=(203, 200) dtype=float64_ref>, <tf.Variable 'b:0' shape=(200,) dtype=float64_ref>, <tf.Variable 'W2:0' shape=(200, 3) dtype=float64_ref>, <tf.Variable 'b2:0' shape=(3,) dtype=float64_ref>]
norming the grads
grads are
[<tf.Tensor 'clip_by_global_norm/clip_by_global_norm/_0:0' shape=(203, 200) dtype=float64>, <tf.Tensor 'clip_by_global_norm/clip_by_global_norm/_1:0' shape=(200,) dtype=float64>, <tf.Tensor 'clip_by_global_norm/clip_by_global_norm/_2:0' shape=(200, 3) dtype=float64>, <tf.Tensor 'clip_by_global_norm/clip_by_global_norm/_3:0' shape=(3,) dtype=float64>]
num batches train: 10
num batches test: 4
INFO:tensorflow:Restoring parameters from /home/user/neural_program_synthesis/models/summaries/RNN/np_mult-5ops/200_state_size-1500_num_samples-100_batch_size-0.005_learning_rate-1000.0_grad_norm-3_num_features-True_norm//model/-3000


In [30]:
def print_matrix(matrix_lst):
    for elem in range(len(matrix_lst[0])):
        for matrix in matrix_lst:
            print(matrix[elem], end=" ")
        print("\n#####################################################################")        

In [31]:
for softmaxe in _softmaxes_train:
    print("#####################################################################")
    print(softmaxe)

#####################################################################
[[  4.20894233e-09   9.99999996e-01   3.65186914e-15]
 [  1.66344416e-13   1.00000000e+00   4.72026788e-14]
 [  1.19399541e-16   8.19469189e-26   1.00000000e+00]
 [  1.57599247e-08   1.31161152e-05   9.99986868e-01]
 [  4.25950999e-14   5.50652986e-19   1.00000000e+00]
 [  3.87161850e-24   1.48345701e-11   1.00000000e+00]
 [  3.27804140e-09   7.35573945e-13   9.99999997e-01]
 [  2.92898131e-13   3.21487947e-18   1.00000000e+00]
 [  3.50887616e-06   9.99794546e-01   2.01945566e-04]
 [  4.20727362e-09   5.05645984e-10   9.99999995e-01]
 [  1.06774362e-12   3.92478420e-01   6.07521580e-01]
 [  1.02917404e-12   1.92182323e-11   1.00000000e+00]
 [  4.40320951e-18   1.14236613e-11   1.00000000e+00]
 [  3.71605784e-09   9.99999995e-01   8.90686854e-10]
 [  1.29656896e-07   4.62988518e-07   9.99999407e-01]
 [  1.73757465e-15   1.00000000e+00   3.61251991e-11]
 [  8.57767652e-08   1.23871123e-09   9.99999913e-01]
 [  2.671564

In [32]:
print_matrix(_softmaxes_test)

[ 0.  1.  0.] [ 0.  0.  1.] [ 0.  0.  1.] [ 0.  0.  1.] [ 0.  0.  1.] 
#####################################################################
[ 0.  1.  0.] [ 0.  0.  1.] [ 0.  0.  1.] [ 0.  0.  1.] [ 0.  0.  1.] 
#####################################################################
[ 0.  0.  1.] [ 0.  1.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] 
#####################################################################
[ 0.  0.  1.] [ 0.  0.  1.] [ 0.  1.  0.] [ 1.  0.  0.] [ 1.  0.  0.] 
#####################################################################
[ 0.  0.  1.] [ 0.  1.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] 
#####################################################################
[ 0.  0.  1.] [ 0.  0.  1.] [ 0.  1.  0.] [ 1.  0.  0.] [ 1.  0.  0.] 
#####################################################################
[ 0.  0.  1.] [ 0.  1.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] 
#####################################################################
[ 0.  0.  1.]

In [25]:
len(_softmaxes_test[0])

100