In [1]:
import pprint
import os
import sys
import numpy as np
from params import get_cfg
from rnn_base import RNN
from mem_sel_rnn import MemRNN
from ops import Operations
from session import run_session, restore_selection_matrixes, predict_form_sess
from data_gen import samples_generator, split_train_test
import pickle
from data_gen import samples_generator, split_train_test

name = '50_state_size-1500_num_samples-100_batch_size-0.005_learning_rate-1000.0_grad_norm-3_num_features-True_norm-True_share_state-8109_seed'
path = '/home/user/neural_program_synthesis/models/summaries/RNN/np_avg_val-4ops/'+name+'/'
#get the global configuration
cfg_path = path+'cfg.p'
cfg = pickle.load(open(cfg_path, 'rb'))
#instantiate containter with the operations avail for the selection
ops = Operations(cfg)
#generate data 
x,y = samples_generator(cfg['train_fn'], (cfg['num_samples'], cfg['num_features']) , cfg['samples_value_rng'], cfg['seed'])
x_train, x_test, y_train, y_test = split_train_test (x, y , cfg['test_ratio'])
#instantiate the mem
mem = MemRNN(cfg, ops)
# instanitae the model graph
model = RNN(cfg, ops, mem)
#restore with given path
model_path = path+'/model'
res = restore_selection_matrixes(model, cfg, x_train, x_test, y_train, y_test, model_path)

timestep 0
timestep 1
timestep 2
timestep 3
timestep 0
timestep 1
timestep 2
timestep 3
[<tf.Variable 'RNN_mem/Params/W_mem:0' shape=(53, 50) dtype=float64_ref>, <tf.Variable 'RNN_mem/Params/b_mem:0' shape=(50,) dtype=float64_ref>, <tf.Variable 'RNN_mem/Params/W2_mem:0' shape=(50, 4) dtype=float64_ref>, <tf.Variable 'RNN_mem/Params/b2_mem:0' shape=(4,) dtype=float64_ref>, <tf.Variable 'RNN_op/Params/W:0' shape=(53, 50) dtype=float64_ref>, <tf.Variable 'RNN_op/Params/b:0' shape=(50,) dtype=float64_ref>, <tf.Variable 'RNN_op/Params/W2:0' shape=(50, 4) dtype=float64_ref>, <tf.Variable 'RNN_op/Params/b2:0' shape=(4,) dtype=float64_ref>]
norming the grads
grads are
[<tf.Tensor 'RNN_op/Grads/clip_by_global_norm/RNN_op/Grads/clip_by_global_norm/_0:0' shape=(53, 50) dtype=float64>, <tf.Tensor 'RNN_op/Grads/clip_by_global_norm/RNN_op/Grads/clip_by_global_norm/_1:0' shape=(50,) dtype=float64>, <tf.Tensor 'RNN_op/Grads/clip_by_global_norm/RNN_op/Grads/clip_by_global_norm/_2:0' shape=(50, 4) dtype

In [2]:
def print_errors(error_lst, name):
    print("")
    for i, error in enumerate(error_lst):
        print(name + "[" + str(i) + "] err is " + str(error))

In [3]:
def print_matrix(total_error, matrix_lst):
    np.set_printoptions(precision=3, suppress=True)
    print("Error for this matrix is", total_error)
    for elem in range(len(matrix_lst[0])):
        print("\n##Elem-"+str(elem)+"--#############################################################")        
        for matrix in matrix_lst:
            print(matrix[elem], end=" ")
       

In [4]:
print_errors(res["total_loss_traind_train"], "sofmax_train_error")
print_errors(res["total_loss_traind_test"], "hardmax_train_error")
print_errors(res["total_loss_testd_train"], "softmax_test_error")
print_errors(res["total_loss_testd_test"], "hardmax_test_error")


sofmax_train_error[0] err is 234.059969215
sofmax_train_error[1] err is 203.50596369
sofmax_train_error[2] err is 289.379285221
sofmax_train_error[3] err is 241.728819209
sofmax_train_error[4] err is 804.301540117
sofmax_train_error[5] err is 277.258183182
sofmax_train_error[6] err is 229.513339013
sofmax_train_error[7] err is 250.692509102
sofmax_train_error[8] err is 277.780344655
sofmax_train_error[9] err is 270.634684538

hardmax_train_error[0] err is 63131.9034609
hardmax_train_error[1] err is 59613.3170262
hardmax_train_error[2] err is 67628.901435
hardmax_train_error[3] err is 66326.7653879
hardmax_train_error[4] err is 71447.8452338
hardmax_train_error[5] err is 65436.2804605
hardmax_train_error[6] err is 66651.3535314
hardmax_train_error[7] err is 64370.6137958
hardmax_train_error[8] err is 66317.5311278
hardmax_train_error[9] err is 71331.0759139

softmax_test_error[0] err is 530.902156964
softmax_test_error[1] err is 266.829958569
softmax_test_error[2] err is 639.096833101


In [14]:
print_matrix(res["total_loss_traind_train"][0], res["softmaxes_traind_train"][0])

Error for this matrix is 234.059969215

##Elem-0--#############################################################
[ 0.905  0.     0.036  0.059] [ 0.671  0.     0.19   0.139] [ 0.227  0.     0.182  0.591] [ 0.005  0.     0.     0.995] 
##Elem-1--#############################################################
[ 0.008  0.     0.013  0.979] [ 0.357  0.     0.355  0.288] [ 0.552  0.     0.207  0.241] [ 0.012  0.     0.01   0.978] 
##Elem-2--#############################################################
[ 0.433  0.     0.051  0.516] [ 0.377  0.     0.167  0.456] [ 0.076  0.     0.075  0.848] [ 0.292  0.     0.083  0.625] 
##Elem-3--#############################################################
[ 0.009  0.     0.014  0.977] [ 0.357  0.     0.354  0.289] [ 0.552  0.     0.207  0.241] [ 0.012  0.     0.01   0.978] 
##Elem-4--#############################################################
[ 0.028  0.     0.02   0.952] [ 0.674  0.     0.222  0.104] [ 0.475  0.     0.108  0.417] [ 0.001  0.     0.     0.9

In [15]:
print_matrix(res["total_loss_traind_test"][0], res["softmaxes_traind_test"][0])

Error for this matrix is 63131.9034609

##Elem-0--#############################################################
[ 1.  0.  0.  0.] [ 1.  0.  0.  0.] [ 0.  0.  0.  1.] [ 0.  0.  0.  1.] 
##Elem-1--#############################################################
[ 0.  0.  0.  1.] [ 0.  0.  1.  0.] [ 1.  0.  0.  0.] [ 0.  0.  0.  1.] 
##Elem-2--#############################################################
[ 0.  0.  0.  1.] [ 0.  0.  0.  1.] [ 0.  0.  0.  1.] [ 0.  0.  0.  1.] 
##Elem-3--#############################################################
[ 0.  0.  0.  1.] [ 1.  0.  0.  0.] [ 1.  0.  0.  0.] [ 0.  0.  0.  1.] 
##Elem-4--#############################################################
[ 0.  0.  0.  1.] [ 1.  0.  0.  0.] [ 0.  0.  0.  1.] [ 0.  0.  0.  1.] 
##Elem-5--#############################################################
[ 0.  0.  0.  1.] [ 1.  0.  0.  0.] [ 1.  0.  0.  0.] [ 0.  0.  0.  1.] 
##Elem-6--#############################################################
[ 1.  0.  0.  0.] 

In [17]:
print_matrix(res["total_loss_traind_test"][0], res["softmaxes_traind_test_mem"][0])

Error for this matrix is 63131.9034609

##Elem-0--#############################################################
[ 0.  0.  0.  1.] [ 0.  1.  0.  0.] [ 0.  1.  0.  0.] [ 0.  1.  0.  0.] 
##Elem-1--#############################################################
[ 0.  1.  0.  0.] [ 1.  0.  0.  0.] [ 1.  0.  0.  0.] [ 0.  1.  0.  0.] 
##Elem-2--#############################################################
[ 0.  1.  0.  0.] [ 1.  0.  0.  0.] [ 1.  0.  0.  0.] [ 1.  0.  0.  0.] 
##Elem-3--#############################################################
[ 0.  0.  1.  0.] [ 1.  0.  0.  0.] [ 0.  1.  0.  0.] [ 0.  1.  0.  0.] 
##Elem-4--#############################################################
[ 0.  0.  0.  1.] [ 0.  0.  0.  1.] [ 0.  1.  0.  0.] [ 0.  1.  0.  0.] 
##Elem-5--#############################################################
[ 0.  0.  1.  0.] [ 1.  0.  0.  0.] [ 0.  1.  0.  0.] [ 0.  1.  0.  0.] 
##Elem-6--#############################################################
[ 0.  0.  0.  1.] 

In [ ]:
seed = 10000
x,y = samples_generator(cfg['train_fn'], (cfg['num_samples'], cfg['num_features']) , cfg['samples_value_rng'], seed)
x_train, x_test, y_train, y_test = split_train_test (x, y , cfg['test_ratio'])
res = predict_form_sess(model, cfg, x_test[0:100,], last_hardmax_state_train, model_path, mode="hard")

In [ ]:
res - y_test[0:100,]

In [ ]:
y_test[0:100,]

In [ ]:
res

In [12]:
len(res["softmaxes_traind_train"])

10