In [1]:
import pprint
import os
import sys
import numpy as np
from params import get_cfg
from rnn_base import RNN
from ops import Operations
from session import run_session, restore_selection_matrixes
from data_gen import samples_generator, split_train_test
import tensorflow as tf
import pickle

path = '/home/user/neural_program_synthesis/models/summaries/RNN/np_mult-5ops/200_state_size-1500_num_samples-100_batch_size-0.005_learning_rate-1000.0_grad_norm-3_num_features-True_norm/'
#get the global configuration
cfg_path = path+'cfg.p'
cfg = pickle.load(open(cfg_path, 'rb'))
#instantiate containter with the operations avail for the selection
ops = Operations(cfg)
#reset graph so that tf dont complain about not found vars
tf.reset_default_graph()
#generate data 
x,y = samples_generator(cfg['train_fn'], (cfg['num_samples'], cfg['num_features']) , cfg['samples_value_rng'], cfg['seed'])
x_train, x_test, y_train, y_test = split_train_test (x, y , cfg['test_ratio'])
# instanitae the model graph
model = RNN(cfg, ops)
#restore with given path
model_path = path+'/model'
_total_loss_traind_train, _softmaxes_traind_train, _total_loss_traind_test, _softmaxes_traind_test,_total_loss_testd_train, _softmaxes_testd_train, _total_loss_testd_test, _softmaxes_testd_test = restore_selection_matrixes(model, cfg, x_train, x_test, y_train, y_test, model_path)

timestep 0
timestep 1
timestep 2
timestep 3
timestep 4
timestep 0
timestep 1
timestep 2
timestep 3
timestep 4
[<tf.Variable 'W:0' shape=(203, 200) dtype=float64_ref>, <tf.Variable 'b:0' shape=(200,) dtype=float64_ref>, <tf.Variable 'W2:0' shape=(200, 3) dtype=float64_ref>, <tf.Variable 'b2:0' shape=(3,) dtype=float64_ref>]
norming the grads
grads are
[<tf.Tensor 'clip_by_global_norm/clip_by_global_norm/_0:0' shape=(203, 200) dtype=float64>, <tf.Tensor 'clip_by_global_norm/clip_by_global_norm/_1:0' shape=(200,) dtype=float64>, <tf.Tensor 'clip_by_global_norm/clip_by_global_norm/_2:0' shape=(200, 3) dtype=float64>, <tf.Tensor 'clip_by_global_norm/clip_by_global_norm/_3:0' shape=(3,) dtype=float64>]
num batches train: 10
num batches test: 4
INFO:tensorflow:Restoring parameters from /home/user/neural_program_synthesis/models/summaries/RNN/np_mult-5ops/200_state_size-1500_num_samples-100_batch_size-0.005_learning_rate-1000.0_grad_norm-3_num_features-True_norm//model/-3000


In [3]:
def print_matrix(total_error, matrix_lst):
    np.set_printoptions(precision=3, suppress=True)
    print("Error for this matrix is", total_error)
    for elem in range(len(matrix_lst[0])):
        print("\n##Elem-"+str(elem)+"--#############################################################")        
        for matrix in matrix_lst:
            print(matrix[elem], end=" ")
       

In [4]:
print_matrix(_total_loss_traind_train, _softmaxes_traind_train)

Error for this matrix is 5.29686961484e-08


##Elem-0--#############################################################
[ 0.  1.  0.] [ 0.  0.  1.] [ 0.  0.  1.] [ 0.  0.  1.] [ 0.  0.  1.] 
##Elem-1--#############################################################
[ 0.  1.  0.] [ 0.  0.  1.] [ 0.  0.  1.] [ 0.  0.  1.] [ 0.  0.  1.] 
##Elem-2--#############################################################
[ 0.  1.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] 
##Elem-3--#############################################################
[ 0.  1.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] 
##Elem-4--#############################################################
[ 0.  1.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] 
##Elem-5--#############################################################
[ 0.  1.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] 
##Elem-6--#############################################################
[ 0.  0.  1.] [ 0.  1.  0

In [5]:
print_matrix(_total_loss_traind_test, _softmaxes_traind_test)

Error for this matrix is 0.0


##Elem-0--#############################################################
[ 0.  1.  0.] [ 0.  0.  1.] [ 0.  0.  1.] [ 0.  0.  1.] [ 0.  0.  1.] 
##Elem-1--#############################################################
[ 0.  1.  0.] [ 0.  0.  1.] [ 0.  0.  1.] [ 0.  0.  1.] [ 0.  0.  1.] 
##Elem-2--#############################################################
[ 0.  1.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] 
##Elem-3--#############################################################
[ 0.  1.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] 
##Elem-4--#############################################################
[ 0.  1.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] 
##Elem-5--#############################################################
[ 0.  1.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] [ 1.  0.  0.] 
##Elem-6--#############################################################
[ 0.  0.  1.] [ 0.  1.  0.] [ 1.  0.  0

In [ ]:
print_matrix(_total_loss_testd_train, _softmaxes_testd_train)

In [ ]:
print_matrix(_total_loss_testd_test, _softmaxes_testd_test)