In [45]:
import pprint
import os
import sys
from params import get_cfg
from rnn_base import RNN
from ops import Operations
from session import run_session, restore_selection_matrixes
from data_gen import samples_generator, split_train_test

#get the global configuration
cfg = get_cfg() 
#instantiate containter with the operations avail for the selection
ops = Operations(cfg)
#reset graph so that tf dont complain about not found vars
tf.reset_default_graph()
#generate data 
x,y = samples_generator(cfg['train_fn'], (cfg['num_samples'], cfg['num_features']) , cfg['samples_value_rng'], cfg['seed'])
x_train, x_test, y_train, y_test = split_train_test (x, y , cfg['test_ratio'])
# instanitae the model graph
model = RNN(cfg, ops)
#restore with given path
path = './summaries/np_add-5ops/test1/model/'
_softmaxes_train, _softmax_train, _softmaxes_test, _softmax_test = restore_selection_matrixes(model, cfg, x_train, x_test, y_train, y_test, path)


timestep 0
timestep 1
timestep 2
timestep 3
timestep 4
timestep 0
timestep 1
timestep 2
timestep 3
timestep 4
[<tf.Variable 'W:0' shape=(53, 50) dtype=float64_ref>, <tf.Variable 'b:0' shape=(50,) dtype=float64_ref>, <tf.Variable 'W2:0' shape=(50, 3) dtype=float64_ref>, <tf.Variable 'b2:0' shape=(3,) dtype=float64_ref>]
norming the grads
grads are
[<tf.Tensor 'clip_by_global_norm/clip_by_global_norm/_0:0' shape=(53, 50) dtype=float64>, <tf.Tensor 'clip_by_global_norm/clip_by_global_norm/_1:0' shape=(50,) dtype=float64>, <tf.Tensor 'clip_by_global_norm/clip_by_global_norm/_2:0' shape=(50, 3) dtype=float64>, <tf.Tensor 'clip_by_global_norm/clip_by_global_norm/_3:0' shape=(3,) dtype=float64>]
INFO:tensorflow:Restoring parameters from ./summaries/np_add-5ops/test1/model/-1950


NameError: name 'num_batches' is not defined

In [40]:
for softmaxe in _softmaxes_train:
    print("#####################################################################")
    print(softmaxe)

#####################################################################
[[ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 0.991  0.     0.009]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 0.985  0.     0.015]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 0.964  0.     0.036]
 [ 0.997  0.     0.003]
 [ 1.     0.     0.   ]
 [ 0.943  0.     0.057]
 [ 1.     0.     0.   ]
 [ 0.996  0.     0.004]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 0.996  0.     0.004]
 [ 0.999  0.     0.001]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 0.999  0.     0.001]
 [ 1.     0.     0.   ]
 [ 1.     0.     0.   ]
 [ 1.     0.     0

In [41]:
for softma in _softmaxes_test:
    print("#####################################################################")
    print(softma)

#####################################################################
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]


In [27]:
_softmax_train.shape

(100, 3)

In [28]:
W2.shape

TensorShape([Dimension(50), Dimension(3)])

In [29]:
W.shape

TensorShape([Dimension(53), Dimension(50)])

In [30]:
init_state.shape

TensorShape([Dimension(100), Dimension(50)])

In [31]:
b.shape

TensorShape([Dimension(50)])

In [32]:
b2.shape

TensorShape([Dimension(3)])