In [29]:
import numpy as np

def apply_adam(w, grad, epsilon, beta1, beta2, alpha, step, m ,v):
  print("w")
  print(w)

  beta1_pow = beta1**step
  beta2_pow = beta2**step
  print("beta1_pow", beta1_pow)
  print("beta2_pow", beta2_pow)
    
  lr_t = alpha * np.sqrt(1 - beta2_pow) / (1 - beta1_pow)
  print("lr_t")
  print(lr_t)

  m_t = beta1 * m + (1 - beta1) * grad
  v_t = beta2 * v + (1 - beta2) * grad * grad
  print("m_t")
  print(m_t)
  print("v_t")
  print(v_t)
    
    
  w = w - lr_t * m_t / (np.sqrt(v_t) + epsilon)
  print("updated w")
  print(w)


In [30]:
grads = np.array([[ 8.23268989e+20, 1.66774029e+20, -9.90043195e+20],
                  [ 8.23268989e+20, 1.66774029e+20, -9.90043195e+20],
                  [ 8.23268989e+20, 1.66774029e+20, -9.90043195e+20],
                  [ 8.23268989e+20, 1.66774029e+20, -9.90043195e+20]], dtype='float32')

'''
grads =  [  8.23268989e+20,   1.66774029e+20,  -9.90043195e+20],
betta1 = array(0.8999999761581421, dtype=float32)
betta2 = array(0.9990000128746033, dtype=float32)
betta1_power = array(0.8999999761581421, dtype=float32)
betta2_power = array(0.9990000128746033, dtype=float32)
aplha   = array(0.10000000149011612, dtype=float32)
epsilon = array(9.99999993922529e-09, dtype=float32)
'''

epsilon = 9.99999993922529e-09
beta1 =  0.8999999761581421
beta2 = 0.9990000128746033
alpha = 0.10000000149011612

step=1

m=np.array([[ 0., 0., 0.],
            [ 0., 0., 0.],
            [ 0., 0., 0.],
            [ 0., 0., 0.]] , dtype='float32')

v=np.array([[ 0., 0., 0.],
            [ 0., 0., 0.],
            [ 0., 0., 0.],
            [ 0., 0., 0.]] , dtype='float32')


w=np.array([[0.02393387,  -0.14345245, 0.01437346 ],
            [-0.14084348, 0.02052397, -0.11966531 ],
            [-0.13571154, -0.04231506, -0.21629484],
            [-0.10692006, 0.0168522,   -0.0307635 ]] , dtype='float32')




In [31]:
apply_adam(w, grads, epsilon, beta1, beta2, alpha, step, m ,v)


w
[[ 0.02393387 -0.14345245  0.01437346]
 [-0.14084348  0.02052397 -0.11966531]
 [-0.13571154 -0.04231506 -0.21629484]
 [-0.10692006  0.0168522  -0.0307635 ]]
beta1_pow 0.8999999761581421
beta2_pow 0.9990000128746033
lr_t
0.0316225659675
m_t
[[  8.23269183e+19   1.66774067e+19  -9.90043458e+19]
 [  8.23269183e+19   1.66774067e+19  -9.90043458e+19]
 [  8.23269183e+19   1.66774067e+19  -9.90043458e+19]
 [  8.23269183e+19   1.66774067e+19  -9.90043458e+19]]
v_t
[[             inf   2.78132176e+37              inf]
 [             inf   2.78132176e+37              inf]
 [             inf   2.78132176e+37              inf]
 [             inf   2.78132176e+37              inf]]
updated w
[[ 0.02393387 -0.24345246  0.01437346]
 [-0.14084348 -0.07947603 -0.11966531]
 [-0.13571154 -0.14231506 -0.21629484]
 [-0.10692006 -0.0831478  -0.0307635 ]]


/usr/local/lib/python3.4/dist-packages/ipykernel/__main__.py:17: RuntimeWarning: overflow encountered in multiply


In [7]:
sqrt(v) + epsilon

TypeError: only length-1 arrays can be converted to Python scalars