In [17]:
import numpy as np
import tensorflow as tf
from data_gen import *
import random

In [21]:
num_features = 2
batch_size = 5
state_size = 4
datatype = tf.float64
num_of_operations = 3


gloabal_seed = round(random.random()*100000)
np.random.seed(gloabal_seed)
tf.set_random_seed(gloabal_seed)
sess = tf.InteractiveSession()

x,y = samples_generator(np_add, (batch_size, num_features) , (-1,1), gloabal_seed)

batchX = tf.Variable(x, dtype=datatype)
state  = tf.Variable(np.zeros([batch_size, state_size]), dtype=datatype)
W      = tf.Variable(np.random.rand(state_size+num_features, state_size), dtype=datatype)
W2     = tf.Variable(np.random.rand(state_size, num_of_operations),dtype=datatype)

batchX.initializer.run()
state.initializer.run()
W.initializer.run()
W2.initializer.run()

In [22]:
def run_pass(batchX, state):
    X_and_state_con = tf.concat([batchX, state], 1)
    print("X_and_state_con")
    print(X_and_state_con.eval())
    layer1          = tf.matmul(X_and_state_con, W)
    print("layer1")
    print(layer1.eval())
    #next_state      = tf.nn.sigmoid(layer1)
    next_state      = tf.tanh(layer1)
    print("next_state")
    print(next_state.eval())
    state_dropped = tf.layers.dropout(next_state, 0.15, training = True)
    print("state_dropped")
    print(state_dropped.eval())
    logits = tf.matmul(state_dropped, W2)
    print("logits")
    print(logits.eval())
    softmax = tf.nn.softmax(logits)
    print("softmax")
    print(softmax.eval())
    return softmax, next_state , logits

In [23]:
state1 = run_pass(batchX, state)[1].eval()

X_and_state_con
[[ 0.87534304  0.9449777   0.          0.          0.          0.        ]
 [ 0.20325639  0.74427945  0.          0.          0.          0.        ]
 [ 0.07102169  0.19365824  0.          0.          0.          0.        ]
 [-0.29769086  0.53162387  0.          0.          0.          0.        ]
 [ 0.73457978  0.39143027  0.          0.          0.          0.        ]]
layer1
[[ 1.32683006  1.41525156  0.85846429  1.48709665]
 [ 0.58915745  0.64187222  0.3836419   0.74724606]
 [ 0.17030111  0.18464868  0.11073263  0.21024663]
 [ 0.00555411  0.02778756  0.00758294  0.14749588]
 [ 0.8984097   0.94798763  0.57939643  0.94041818]]
next_state
[[ 0.86847244  0.88860414  0.69546559  0.90278911]
 [ 0.52928936  0.56617298  0.36586607  0.63350312]
 [ 0.1686736   0.18257837  0.11028225  0.20720256]
 [ 0.00555405  0.02778041  0.00758279  0.14643551]
 [ 0.71552264  0.73887065  0.52222661  0.73541433]]
state_dropped
[[ 1.02173229  1.04541664  0.81819481  1.06210484]
 [ 0.62269337

In [24]:
state2 = run_pass(batchX, state1)[1].eval()

X_and_state_con
[[ 0.87534304  0.9449777   0.86847244  0.88860414  0.69546559  0.90278911]
 [ 0.20325639  0.74427945  0.52928936  0.56617298  0.36586607  0.63350312]
 [ 0.07102169  0.19365824  0.1686736   0.18257837  0.11028225  0.20720256]
 [-0.29769086  0.53162387  0.00555405  0.02778041  0.00758279  0.14643551]
 [ 0.73457978  0.39143027  0.71552264  0.73887065  0.52222661  0.73541433]]
layer1
[[ 4.33090215  3.79366251  2.22132578  2.4408988 ]
 [ 2.47411516  2.15288106  1.20906387  1.37686881]
 [ 0.77272682  0.6688732   0.37156966  0.4140294 ]
 [ 0.18560087  0.19596798  0.08100298  0.23396901]
 [ 3.32766188  2.8729417   1.66121931  1.72169202]]
next_state
[[ 0.99965392  0.99898684  0.97674419  0.98494741]
 [ 0.98590808  0.97337795  0.83639846  0.88024818]
 [ 0.64851225  0.58423819  0.35536392  0.39188864]
 [ 0.18349866  0.19349731  0.08082627  0.2297912 ]
 [ 0.99742901  0.99362854  0.93038123  0.93806645]]
state_dropped
[[ 1.17606343  1.17527864  1.14911082  1.15876166]
 [ 1.15989186

In [16]:
state3 = run_pass(batchX, state2)[1].eval()

X_and_state_con
[[-0.48194403 -0.6537931  -0.85560739 -0.70845758 -0.86175901 -0.91634596]
 [-0.31554519 -0.75737679 -0.86886513 -0.70403074 -0.86303768 -0.92530353]
 [ 0.25901108 -0.95455789 -0.85810936 -0.61887913 -0.80724577 -0.91586173]
 [ 0.30868902  0.13641044  0.3868672   0.31912044  0.42924907  0.46767314]
 [ 0.09877885 -0.03163367  0.01164019  0.03119781  0.0376305   0.01620849]]
layer1
[[-1.99743607 -1.53417104 -2.29186818 -3.11256198]
 [-2.0325854  -1.51650061 -2.30475129 -3.16475529]
 [-1.96562431 -1.35525399 -2.11392561 -3.07129776]
 [ 0.87549632  0.75034824  1.00605854  1.4037482 ]
 [ 0.04003409  0.06159064  0.07654249  0.07183651]]
next_state
[[-0.96384599 -0.91113567 -0.97977334 -0.99604966]
 [-0.96625888 -0.90808588 -0.98028278 -0.99644053]
 [-0.96151669 -0.87528771 -0.97125187 -0.99571054]
 [ 0.70415592  0.63535666  0.76412687  0.88615915]
 [ 0.04001272  0.06151288  0.07639336  0.0717132 ]]
logits
[[-2.94695597 -2.35917369 -1.86398304]
 [-2.94626789 -2.36060327 -1.865