In [17]:
import numpy as np
import tensorflow as tf
from data_gen import *
import random

In [21]:
num_features = 2
batch_size = 5
state_size = 4
datatype = tf.float64
num_of_operations = 3


gloabal_seed = round(random.random()*100000)
np.random.seed(gloabal_seed)
tf.set_random_seed(gloabal_seed)
sess = tf.InteractiveSession()

x,y = samples_generator(np_add, (batch_size, num_features) , (-1,1), gloabal_seed)

batchX = tf.Variable(x, dtype=datatype)
state  = tf.Variable(np.zeros([batch_size, state_size]), dtype=datatype)
W      = tf.Variable(np.random.rand(state_size+num_features, state_size), dtype=datatype)
W2     = tf.Variable(np.random.rand(state_size, num_of_operations),dtype=datatype)

batchX.initializer.run()
state.initializer.run()
W.initializer.run()
W2.initializer.run()

In [34]:
def run_pass(batchX, state):
    X_and_state_con = tf.concat([batchX, state], 1)
    print("X_and_state_con")
    print(X_and_state_con.eval())
    layer1          = tf.matmul(X_and_state_con, W)
    print("layer1")
    print(layer1.eval())
    #next_state      = tf.nn.sigmoid(layer1)
    next_state      = tf.nn.relu(layer1)
    print("next_state")
    print(next_state.eval())
    state_dropped = tf.layers.dropout(next_state, 0.15, training = True)
    print("state_dropped")
    print(state_dropped.eval())
    logits = tf.matmul(state_dropped, W2)
    print("logits")
    print(logits.eval())
    softmax = tf.nn.softmax(logits)
    print("softmax")
    print(softmax.eval())
    softmax_l2_losts = tf.nn.l2_loss(100*softmax)
    print("softmax_l2_losts")
    print(softmax_l2_losts.eval())
    return softmax, next_state , logits

In [35]:
state1 = run_pass(batchX, state)[1].eval()

X_and_state_con
[[ 0.87534304  0.9449777   0.          0.          0.          0.        ]
 [ 0.20325639  0.74427945  0.          0.          0.          0.        ]
 [ 0.07102169  0.19365824  0.          0.          0.          0.        ]
 [-0.29769086  0.53162387  0.          0.          0.          0.        ]
 [ 0.73457978  0.39143027  0.          0.          0.          0.        ]]
layer1
[[ 1.32683006  1.41525156  0.85846429  1.48709665]
 [ 0.58915745  0.64187222  0.3836419   0.74724606]
 [ 0.17030111  0.18464868  0.11073263  0.21024663]
 [ 0.00555411  0.02778756  0.00758294  0.14749588]
 [ 0.8984097   0.94798763  0.57939643  0.94041818]]
next_state
[[ 1.32683006  1.41525156  0.85846429  1.48709665]
 [ 0.58915745  0.64187222  0.3836419   0.74724606]
 [ 0.17030111  0.18464868  0.11073263  0.21024663]
 [ 0.00555411  0.02778756  0.00758294  0.14749588]
 [ 0.8984097   0.94798763  0.57939643  0.94041818]]
state_dropped
[[ 0.          0.          1.00995799  1.74952547]
 [ 0.        

In [31]:
state2 = run_pass(batchX, state1)[1].eval()

X_and_state_con
[[ 0.87534304  0.9449777   1.32683006  1.41525156  0.85846429  1.48709665]
 [ 0.20325639  0.74427945  0.58915745  0.64187222  0.3836419   0.74724606]
 [ 0.07102169  0.19365824  0.17030111  0.18464868  0.11073263  0.21024663]
 [-0.29769086  0.53162387  0.00555411  0.02778756  0.00758294  0.14749588]
 [ 0.73457978  0.39143027  0.8984097   0.94798763  0.57939643  0.94041818]]
layer1
[[ 5.89864581  5.06631294  2.84040911  3.00865419]
 [ 2.71885603  2.35779467  1.30402808  1.47250741]
 [ 0.77931526  0.67438342  0.3741095   0.41660545]
 [ 0.18665614  0.19702299  0.0814331   0.23453769]
 [ 3.91777916  3.3476774   1.89052842  1.93269955]]
next_state
[[ 5.89864581  5.06631294  2.84040911  3.00865419]
 [ 2.71885603  2.35779467  1.30402808  1.47250741]
 [ 0.77931526  0.67438342  0.3741095   0.41660545]
 [ 0.18665614  0.19702299  0.0814331   0.23453769]
 [ 3.91777916  3.3476774   1.89052842  1.93269955]]
state_dropped
[[ 0.          5.96036816  3.34165777  3.53959316]
 [ 3.19865415

In [16]:
state3 = run_pass(batchX, state2)[1].eval()

X_and_state_con
[[-0.48194403 -0.6537931  -0.85560739 -0.70845758 -0.86175901 -0.91634596]
 [-0.31554519 -0.75737679 -0.86886513 -0.70403074 -0.86303768 -0.92530353]
 [ 0.25901108 -0.95455789 -0.85810936 -0.61887913 -0.80724577 -0.91586173]
 [ 0.30868902  0.13641044  0.3868672   0.31912044  0.42924907  0.46767314]
 [ 0.09877885 -0.03163367  0.01164019  0.03119781  0.0376305   0.01620849]]
layer1
[[-1.99743607 -1.53417104 -2.29186818 -3.11256198]
 [-2.0325854  -1.51650061 -2.30475129 -3.16475529]
 [-1.96562431 -1.35525399 -2.11392561 -3.07129776]
 [ 0.87549632  0.75034824  1.00605854  1.4037482 ]
 [ 0.04003409  0.06159064  0.07654249  0.07183651]]
next_state
[[-0.96384599 -0.91113567 -0.97977334 -0.99604966]
 [-0.96625888 -0.90808588 -0.98028278 -0.99644053]
 [-0.96151669 -0.87528771 -0.97125187 -0.99571054]
 [ 0.70415592  0.63535666  0.76412687  0.88615915]
 [ 0.04001272  0.06151288  0.07639336  0.0717132 ]]
logits
[[-2.94695597 -2.35917369 -1.86398304]
 [-2.94626789 -2.36060327 -1.865